import os
import datetime

def generate_risk_report(claim_data, fraud_result, indicators, ocr_analysis=None):
    """Generate a detailed AI risk report"""
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    fraud_prob = fraud_result.get("fraud_probability", 0)

    if fraud_prob >= 70:
        recommendation = "REJECT - High fraud probability. Escalate for investigation."
        final_decision = "REJECTED"
    elif fraud_prob >= 40:
        recommendation = "HOLD - Medium risk. Requires additional verification and documents."
        final_decision = "PENDING REVIEW"
    else:
        recommendation = "APPROVE - Low fraud risk. Standard processing."
        final_decision = "APPROVED"

    report = f"""
╔══════════════════════════════════════════════════════════════════╗
║           POLICYPILOT AI - INSURANCE CLAIM RISK REPORT          ║
╚══════════════════════════════════════════════════════════════════╝

Report Generated  : {timestamp}
Report ID         : RPT-{claim_data.get('claim_id', 'N/A')}-{datetime.datetime.now().strftime('%Y%m%d')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                        CLAIM INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Claim ID          : {claim_data.get('claim_id', 'N/A')}
Policy Number     : {claim_data.get('policy_number', 'N/A')}
Customer Name     : {claim_data.get('customer_name', 'N/A')}
Claim Amount      : ₹{claim_data.get('claim_amount', 0):,.2f}
Hospital Name     : {claim_data.get('hospital_name', 'N/A')}
Incident Date     : {claim_data.get('incident_date', 'N/A')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                         AI FRAUD ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Fraud Score       : {fraud_prob:.1f} / 100
Risk Percentage   : {fraud_prob:.1f}%
Risk Level        : {fraud_result.get('risk_level', 'Unknown')}
Prediction        : {fraud_result.get('risk_label', 'N/A')}
Confidence Score  : {fraud_result.get('confidence_score', 0):.1f}%

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                      SUSPICIOUS INDICATORS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
    for i, indicator in enumerate(indicators, 1):
        report += f"{i}. {indicator}\n"

    if ocr_analysis:
        report += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                      DOCUMENT ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Document Completeness : {ocr_analysis.get('completeness_score', 0)}%
Word Count            : {ocr_analysis.get('word_count', 0)}
Missing Fields        : {', '.join(ocr_analysis.get('missing_fields', [])) or 'None'}
Suspicious Terms      : {', '.join(ocr_analysis.get('suspicious_keywords', [])) or 'None found'}
"""

    report += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                    RECOMMENDATION & DECISION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Recommendation    : {recommendation}
Final Decision    : {final_decision}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This report was generated by PolicyPilot AI - Automated Fraud Detection System
For queries, contact: admin@policypilot.com
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
    return report, final_decision

def save_report(report_text, claim_id):
    """Save report to file"""
    os.makedirs("reports", exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"reports/report_{claim_id}_{timestamp}.txt"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report_text)
    return filename

def generate_pdf_report(report_text, claim_id):
    """Generate PDF report"""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import HexColor
        import io

        os.makedirs("reports", exist_ok=True)
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"reports/report_{claim_id}_{timestamp}.pdf"

        doc = SimpleDocTemplate(filename, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Title'],
            fontSize=18,
            textColor=HexColor('#1a237e'),
            spaceAfter=12
        )

        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['Normal'],
            fontSize=10,
            spaceAfter=6,
            fontName='Courier'
        )

        story.append(Paragraph("PolicyPilot AI - Risk Report", title_style))
        story.append(Spacer(1, 12))

        for line in report_text.split('\n'):
            if line.strip():
                clean_line = line.replace('╔', '').replace('╗', '').replace('║', '').replace('╚', '').replace('╝', '').replace('━', '-')
                story.append(Paragraph(clean_line, body_style))

        doc.build(story)
        return filename
    except Exception as e:
        return None
